version: '3.9'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${DJANGO_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app/
  postgres:
    image: postgres:latest
    container_name: postgres-db  
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: